name: Publish Terraform parser

on:
  workflow_dispatch:
  
jobs:
  publishWindows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ace-terraform-parser
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      run: go build -o ace-terraform-parser.dll -buildmode=c-shared parser.go
  publishLinux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ace-terraform-parser
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      run: go build -o ace-terraform-parser.dll -buildmode=c-shared parser.go
